### PR TITLE
Asynch Actions refactoring!

### PR DESCRIPTION
**Pull request by facontidavide**
Hi

this PR contains 3 commits. I suggest to review them one by one

### Remove copy and paste related to ActionNode 6e31f5d69a84e8c55334fc9e1bb7d2b49bac87fa

This commit looks intimidating but it is pretty simple and it __does NOT__ change the behavior of the library.

In all your ControlNodes there was some special code related to children of type ActionNode.
The idea is: if you need to execute some special code when you tick() a Node, just displace that code inside the tick() itself !!!

As a consequence, the resulting code is more readable and shorter.

I insist: the logic AND the run-time behavior is completely unchanged!!!

### Remove memory leaks ba982f70cf7a1ae802b674c1276b848df000c3ed
 
The fact that the unit test was ridden with memory leaks made difficult to find real problems. Fixed.

### Actions Zoo cca04249993e054d845f50083fcbe768ab498c93

You gave for granted that action requires their own thread. This might be true or not. 
I added the Nodes of type

- [AsyncActionNode](https://github.com/facontidavide/Behavior-Tree/blob/dev_async/include/behavior_tree_core/action_node.h#L79): the same you implemented, with it's own thread and the TickEngine.
- [SimpleActionNode](https://github.com/facontidavide/Behavior-Tree/blob/dev_async/include/behavior_tree_core/action_node.h#L51): a very easy to build ActionNode that requires only a function pointer that is executed when tick() is invoked. It served me well in the past

Cheers

### CODE REVIEW

**Comment by facontidavide** [comment]
Whooops. Failing unit test... I have to check this out

**Comment by miccol** [comment]
Sure! I will!
Thanks

**Comment by facontidavide** [comment]
Ok. 

I found out that the error was already latent in your code, but it was not visible in the test because you never deleted the pointers (causing memory leaks).

https://travis-ci.org/facontidavide/Behavior-Tree/builds

I understand the problem but I am not 100% happy with the solution I propose in 210ac77c863a805e672d97dbc24e1e1946c1c937

Basically, we are screwed by the order of the destructors:

       ~ActionNodeTest -> AsyncActionNode -> ActionNode -> etc. 

The application fails [here](https://github.com/facontidavide/Behavior-Tree/blob/dev_async/src/action_node.cpp#L73) because after the invocation of __~ActionNodeTest__ the __vtable__ of the derived class is deleted and the funtion asyncTick() becomes a pure virtual.

The solution is to avoid making asynTick and halt() pure virtuals, but honestly it feels like a workaround.

it should work, though.

**Comment by facontidavide** [comment]
Are you ready to merge? Any question or suggestion? Request for change?

**Comment by miccol** [comment]
Looks awesome, as usual.
Can we keep the name ActionNode for the asyncronous actions and name SyncActionNode for the SimpleActionNode? 
Moreover, would it be possible to let the user keep implementing the function tick() for any leaf node?(i.e. without changing the name of the function to implement according to the node type)

**Comment by facontidavide** [comment]
Hi,

What we can do, if you agree is:

1) Rename ActionNode to **ActionNodeBase**
2) Rename AsyncActionNode to **ActionNode**.

__But__ I would **not** change the name of SimpleActionNode to SyncActionNode, since thar class is not about being synchornous or asynchronous, but about using **dependency injection instead of inheritance**.

UPDATED:

About the tick() function, I did not find a solution, __not even using the__ [Curiously Recursive Template Pattern](https://www.fluentcpp.com/2017/05/12/curiously-recurring-template-pattern/).

The ControlNode or DecoratorNode would always call the MyAction::tick() instead of the ActionNode::tick()

**Comment by facontidavide** [comment]
Note: there is something about the logic and timing of the asynchronous Action that it is not 100% clear to me. But I didn't want to change this in this PR. We will talk about that by email if you want.

This PR, just rewrite the code of the ControlNodes, but does not change your logic.

**Comment by miccol** [comment]
Looks great.
I still have problem understanding why you renamed tick() to asyncTick()

**Comment by facontidavide** [comment]
It is a problem of inheritance and polymorphism.

Let's suppose that we have this class hierarchy.

        UserDefinedAction -> ActionNode -> LeafNode -> TreeNode

All of them override the function __tick()__.
Suppose that we have a ControlNode (or a DecoratorNode) that is the parent of an ActionNode.
We are trying to avoid to write [code like this](https://github.com/miccol/Behavior-Tree/blob/master/src/sequence_node.cpp#L37-L64), which treats differently the  Actions.

In other words, ControlNode must call __tick()__, whatever the children type is.

We have now a problem. Based on the way we created a separate thread, triggered by TickEngine, ideally we want:

1)  the ControlNode should invoke the implementation **ActionNode::tick()**.
2) **ActionNode::tick()** should send a signal using TickEngine and the method __waitForTick()__ should invoke  **UserDefinedAction::tick()**.

Goal 2) can be achieved using the Curiously Recursive Template Pattern, but I did NOT find a way to achieve goal 1), since **UserDefinedAction::tick()** will always override **ActionNode::tick()**

If you find a solution, let me know.

**Comment by facontidavide** [comment]
I found a solution... check the code in 1596d607e624c2982ea3ebedb4f6d30552a7b9f5

Basically I add an intermediate method that is called __executeTick()__ that is simply: 

```c++
BT::NodeStatus BT::TreeNode::executeTick()
{
    return tick();
}
```

__But__ only in the case of __ActionNode__ is overridden.

Mission accomplished

**Comment by facontidavide** [comment]
I know I was not supposed to do it in this PR, but I added this commit 1cada0c951445ab5e3581e22614022d63900ca01
that remove some dead-code.

**The bigger changes can be found in the decorators. if you want to discuss those changes in a different PR, let me know, and I will revert them.**

**Pull request merged**
