### PR TITLE
Enabled an action node's worker thread to break upon destruction of t…

### PR DESCRIPTION
**Pull request by mjeronimo**
…he node. 

I'm working on an app that does dynamic creation of behavior trees to execute tasks and then destroys the behavior tree. As the action_node is currently implemented, there is no way to break out of the node's thread.

### CODE REVIEW

**Comment by facontidavide** [comment]
Hi @mjeronimo 

Me and @miccol have been working in the last month on the refactoring of this library. You can find it here: https://github.com/Eurecat/BehaviorTree.CPP

We have already addressed this problem in exactly the same way, but I recentry realized that this solution has a problem too, since there is a thread unsafe access to the vtable of the class during destruction. 
You will frequently crash at destruction time with the error "pure virtual function called"

Please refer to this:
 
https://github.com/google/sanitizers/wiki/ThreadSanitizerPopularDataRaces#data-race-on-vptr

The solution is to stop and join the thread in a different "cleanup" method thst MUST not be invoked by the destructor but explicitly by the user's code.

**Comment by mjeronimo** [comment]
@facontidavide Ok, thanks for the reference. I'll check it out. I see from a quick scan of the new repo that you're adding blackboard support. That will be helpful. I'd also like to dynamically create the BT based on a text-based description (XML, etc.). Any plans for that?

**Comment by facontidavide** [comment]
> I'd also like to dynamically create the BT based on a text-based description (XML, etc.). Any plans for that?

Are you kidding ;) ?

https://github.com/Eurecat/BehaviorTree.CPP/blob/devel/examples/t02_factory_tree.cpp

https://github.com/Eurecat/BehaviorTree.CPP/blob/devel/examples/crossdoor_example.cpp

**Comment by mjeronimo** [comment]
Super! Will this include an XML schema so that the incoming plan can be validated on-the-fly? I'll start digging into the code to understand what's there.

**Comment by facontidavide** [comment]
You got me...

It will

**Comment by mjeronimo** [comment]
@facontidavide Thanks for the responses. Glad to see the new features.

**Comment by miccol** [comment]
Hi @mjeronimo , as Davide mentioned, we are addressing this issue in the new version of this library. Thank you!

**Comment by mjeronimo** [comment]
Yes, thanks @miccol. I'll check out the new version this week.

**Pull request closed without merging**
