### PR TITLE
Preliminary changes to add tracing/logging

### PR DESCRIPTION
**Pull request by facontidavide**
Hi,

this first PR create the initial infrastructure to create a sophisticated tracing/logging/publishing mechanism to observe or save state transitions.

The important things to consider are:

1) **UID** added to TreeNode, to make easier the tracking of state changes using less memory on file. Not used yet.

2) I created an initial version of a **Flatbuffers** definition file. Don't spend too much time reviewing it, it may change once I get to that part. if you are not familiar, with it, Flatbuffers is a serialization library much faster that Protobuffers, Boot::serialize and, of course, ROS serialization ;)

3) Loggers will inherit from the abstract class **StatusChangeLogger**. Right now the most trivial logger (which print to std:.cout) is implemented. You can see it in action with the added example **crossdoor_example.cpp**.

4) I realized that the **Decorators** didn't set the child to IDLE as they should: 4a51d3b956fad58d7f6b7042ec49388e4e76bd46 .

5) Check also the commit 6666f6dbea2b5764fc9a5866570ab5c5655df6f5 and tell me if you agree with the logic.

6) Removed **DEBUG_STDOUT**. I know this might be controversial ;) but I think the new Logging infrastructure is sufficiently verbose, when the option **showsTransitionToIdle**() is turned on.

Cheers

Davide

### CODE REVIEW

**Comment by miccol** [comment]
I know, but the behavior of, for example, Sequence(Condition1,Condition2, Action) must be identical to the one of Sequence(Sequence(Condition1,Condition2), Action). But if the second sequence of the second BT (i.e. Sequence(Condition1,Condition2)) returns Running, them the action gest halted. Behavior that does not happen to the former BT.

**Comment by facontidavide** [comment]
What you described will not happen.  The RUNNING state is NOT returned in any of these cases.
this is because the RUNNING state is set at the beginning, but overwritten later before exit here https://github.com/facontidavide/Behavior-Tree/blob/devel/src/tree_node.cpp#L29 .

I prepared a piece of code that you can use to verify that what I say is true 

```c++ 
class SuccessCondition: public BT::ConditionNode
{
public:
    SuccessCondition(const std::string& name): BT::ConditionNode(name) {}
    BT::NodeStatus tick() override { return BT::NodeStatus::SUCCESS; }
};

int main(int argc, char** argv)
{
    // Nodes instances
    SuccessCondition condition1("condition1");
    SuccessCondition condition2("condition2");
    SimpleActionNode action("action", []() {
        return BT::NodeStatus::SUCCESS;
    });
    BT::SequenceNode seq1("seq1");
    BT::SequenceNode seq2("seq2");

    if( 1 ) // Sequence(Condition1,Condition2, Action)
    {
        seq1.addChild( &condition1 );
        seq1.addChild( &condition2 );
        seq1.addChild( &action );
    }
    else{ // Sequence(Sequence(Condition1,Condition2), Action)
        seq1.addChild( &seq2 );
        {
            seq2.addChild( &condition1 );
            seq2.addChild( &condition2 );
        }
        seq1.addChild( &action );
    }

    auto ret = seq1.executeTick();
    std::cout << "returned " << ret << std::endl;
}
```

**Comment by miccol** [comment]
Yep, you are right. But still, `Status()` in a public method. A user can use that method for any kind of logic and the two tree above should have always the same return status.  Don't you think?

**Comment by facontidavide** [comment]
Can you provide an example based on the one I gave you? I am 90% sure that the user will not be able to see any difference between these two cases. Prove me wrong ;)
 
By the way, setStatus() is public, as you pointed out, but it is always overwritten by the setStatus in executeTick().

This is very important, because the user might accidentally create an action that does

```c++
NodeStatus MyAction::tick()
{
  // the following code makes no sense, it is most probably an error
   setStatus(FAILURE);
   return SUCCESS;
}
```

In this case, thanks to the executeTick(), the status will actually be SUCCESS and the transition to FAILURE is never seen by the  rest of the tree.

Actually, it am realizing that maybe we should just remove setStatus from the public interface!
At the end of the day, we always want tick() to return the correct state.

What do you think?

**Comment by facontidavide** [comment]
WTF!!!

On, I have a problem related to the last commit.
Some unit test fails, but it not a big deal apparently, since some states are supposed to be IDLE with the new logic.

On the other hand, we have a FATAL error in

       TEST_F(SequenceTripleActionTest, TripleAction))

here the behavior is completely messed up.
Since a child return RUNNING set the previous children to IDLE, the action_1 and action_2 is repeated over and over again, whilst action_3 is never executed :(

this are the transitions:
```
root_sequence: IDLE -> RUNNING
action_1: IDLE -> RUNNING
action_1: RUNNING -> SUCCESS
action_2: IDLE -> RUNNING
action_1: SUCCESS -> IDLE
action_1: IDLE -> RUNNING
action_2: RUNNING -> IDLE

action_1: RUNNING -> SUCCESS
action_2: IDLE -> RUNNING
action_1: SUCCESS -> IDLE
action_1: IDLE -> RUNNING
action_2: RUNNING -> IDLE
action_1: RUNNING -> SUCCESS
action_2: IDLE -> RUNNING
action_1: SUCCESS -> IDLE
action_1: IDLE -> RUNNING
action_2: RUNNING -> IDLE
```

**I believe the commit c0f29d3b099b5a6fddec2024b764f4b3fe6e53eb must be reverted.**

Please take a look and confirm it.

**Comment by miccol** [comment]
I agree!

2018-05-30 14:53 GMT+02:00 Davide Faconti <notifications@github.com>:

**Comment by facontidavide** [comment]
All right, reverted. Unless you have any change to propose, can we merge ? ;)

**Comment by miccol** [comment]
yep! merged.

**Pull request merged**
