### PR TITLE
Plugins

### PR DESCRIPTION
**Pull request by facontidavide**
Hi,

with commit d0e83dea3027e219e623c4d0b9036ec2224dc5cb it is now possible to deploy one or more tree nodes as a plugin (dynamically loaded shared library).

Examples have been updated accordingly. See https://github.com/Eurecat/BehaviorTree.CPP/blob/devel/examples/t02_factory_tree.cpp#L64

The plugin approach is optional and the old method (static linking) is still valid.

### CODE REVIEW

**Comment by facontidavide** [comment]
apparently there is a problem I need o fix. I know which one it is, will fix it on Monday

**Comment by facontidavide** [comment]
Ok, I just pushed a commit that should solve the problem about thread safety of the vptr of ActionNode (refer to the email I sent you).

If you find a more clever way to deal with this issue, let me know.
In my opinion ActionNode is fundamentally broken, but this is another story...

**Comment by miccol** [comment]
I think there is some instantiation error somewhere. Do you want me to dig into this?

https://travis-ci.org/miccol/Behavior-Tree/jobs/437680984#L708-L710

**Comment by facontidavide** [comment]
No, the problem is the one about the vptr I mentioned. I just pushed a fix

https://github.com/miccol/Behavior-Tree/pull/31/commits/0080f0919025a2059ac8400f1a9b29c5c2db5c71

**Comment by miccol** [comment]
great!

**Pull request merged**
