### PR TITLE
Ewerlopes dev

### PR DESCRIPTION
**Pull request by ewerlopes**
Hi again.

So, after looking the code a bit more I have made some changes. Specially, I created a folder for holding together the example. Using the word "Template" as a way of demonstrating the code usage don't sound a good idea. So, it is on a new folder now. I adjust the CMakeList for outputting the sample code in a named folder. Also, the compilation process now generates the shared lib (folder /lib) under success.

I also took the liberty for creating a README. =)

Regards.

### CODE REVIEW

**Comment by miccol** [comment]
Hi, thank you for your improvements. I am a bit busy now, I will get back to you soon, we should be careful with the new includes of the GLUT library you made.
In the readme we could just redirect to the user manual (the pdf file).

I think we should keep the source files in the /src directory. If we want to separate the source of the application from the source from the application library, then we should have two separate folders /src and /lib (matter of tastes).

**Comment by ewerlopes** [comment]
Well.. There could be another solution to the problem... But, the simple preprocessor checking solved the issue on Mac El Capitan. Of course, there should be a better way to do it. So, it must be addressed in further work.

Well. I confess I really didn't noticed the user manual until make the "git clone". My suggestion is to keep a good README, maybe with a bit of explanation from the given manual. This may help to attract some collaborators and give a first impression for the  "passer-by".

Well.. regarding source file location.. I suggest not to blend it much with the example code.

**Comment by miccol** [comment]
OK, maybe we should mention that in the readme file.

About the folder structure I was thinking to have something like: 

/src  <- application source
/include <-application header 
 /lib/src <- library source (BT stuff e.g. ActionNode.cpp)
/lib/include <- library header (e.g. ActionNode.h)

So we separate the application (a specific BT) from the library (BT implementation).

Anyway, the reason why the structure is like that in github is because I want the user to have a single copy of the BT implementation (source code). Then from every project the user includes the compiled library. Imagine a user (like me) that has several BT projects. It would be overkill to have the same copy of the source code of BT++ in each project.

What do you think?

**Comment by ewerlopes** [comment]
Humm... That sounds reasonable... I hope to find some spare time to go over this much careful...

**Comment by miccol** [comment]
Time is what is always lacking XD.
I will test the changes you made to be extrasure that all the dependency are OK  then I will merge the branches, (I am sure you tested everything, but especially in ubuntu there are always surprises).

Again, thanks for the improvements and looking forward to further collaborations.

**Comment by ewerlopes** [comment]
Time.. time.. time... :D
Yes. Do it! I tested on my Mac (El Capitan) and on my Ubuntu 14.04.. And.. it all passed (considering the satisfactions of the given dependencies).

I think we should also do some work on the following points:
- A better source code documentation (Using Oxygen, for instance). It would be interesting to have a standard.html documentation..
- A bash script for automating the compilation (installation) procedure.

**Comment by ewerlopes** [comment]
And, by the way... I am gonna go over your research papers (regarding learning in BT) during the weekend. Looking for insights to my PhD research. :D

Nice papers... I should say.

**Comment by miccol** [comment]
Tested on El Capitan (I only have Ubuntu on a VM now). I am going to merge now. I will restructure the project folder later based on our discussion

Thanks

**Comment by ewerlopes** [comment]
Nice! Thank you for accepting the changes.

**Pull request merged**
